FROM ubuntu:18.04
  
#COPY requirements.txt ./requirements.txt
  
RUN apt-get update
RUN apt-get upgrade -y
RUN apt install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3.7
RUN apt-get install -y python3-pip

RUN apt install -y nginx
RUN apt install -y libnginx-mod-rtmp
RUN apt install -y rtmpdump

#RUN pip3 install -r requirements.txt


RUN mkdir -p /workdir
WORKDIR /workdir
COPY nginx.conf /etc/nginx/nginx.conf
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

RUN export LC_ALL=C.UTF-8
RUN export LANG=C.UTF-8


#RUN service nginx restart
#CMD ["/bin/bash"]
#CMD ["service", "nginx", "restart"]
#RUN /etc/init.d/nginx restart

#CMD ["/bin/bash"]
CMD service nginx start
